### ISSUE TITLE
Is it possible to use YOLO or FasterRCNN?

### ISSUE THREAD

**Issue by fiorano10** [intel/ros_intel_movidius_ncs#87]
Is it possible to run YOLO or FasterCNN instead of tiny YOLO on 2X movidius?

**Comment by xhuan28** [comment]
FasterCNN and YOLO are not supported, because some types of layers, such as ROIAlign layer, etc,  are not supported by NCSDK natively.
You can refer [here](https://github.com/movidius/ncsdk/blob/master/docs/release_notes.md#firmware-features) for all the supported layer types by NCSDK.
You can also submit your request to [NCS developer forum](https://ncsforum.movidius.com/discussions). They may add it in their future plan.

**Comment by fiorano10** [comment]
What about Yolov2/3?

**Comment by omyoo7** [comment]
Can we use it for recognition of running Video on the fly?
I want to know that when a video is running and in between an add is come it should able to recognize whether is it a movie or add.
?

**Comment by xhuan28** [comment]
@fiorano10, the same as YoLo.
